# Generated by Django 4.1.1 on 2022-09-21 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hacker_id', models.IntegerField(unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=255)),
                ('by', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('hackernews', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('descendants', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('parent', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
