# Generated by Django 4.1.1 on 2022-09-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChilRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hacker_id', models.IntegerField(unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=255)),
                ('by', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('hackernews', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_child', to='mynews.items')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_parent', to='mynews.items')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
