# Generated by Django 4.1.1 on 2022-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_parentchilrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
