# Generated by Django 4.1.1 on 2022-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0003_alter_items_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='hacker_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parentchilrelationship',
            name='hacker_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
