# Generated by Django 4.1.1 on 2022-09-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0004_alter_items_hacker_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='by',
        ),
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='dead',
        ),
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='hacker_id',
        ),
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='hackernews',
        ),
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='time',
        ),
        migrations.RemoveField(
            model_name='parentchilrelationship',
            name='type',
        ),
    ]
