# Generated by Django 4.0.7 on 2022-09-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0005_remove_parentchilrelationship_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('-created_at',)},
        ),
    ]
